repos:
- repo: https://github.com/ambv/black
  rev: 25.1.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-docstrings]
    additional_dependencies: [flake8-docstrings]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
